package mx.com.quartz.persistence.entities;
// Generated 31/07/2019 10:40:26 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Anime generated by hbm2java
 */
@Entity
@Table(name = "Anime", catalog = "garnet")
public class Anime implements java.io.Serializable {

	private Integer idAnime;
	private Autor autor;
	private Clasificacion clasificacion;
	private Genero genero;
	private String nombre;
	private String sinopsis;
	private Integer calificacion;
	private Set<ElencoAnime> elencoAnimes = new HashSet<ElencoAnime>(0);
	private Set<Capitulo> capitulos = new HashSet<Capitulo>(0);

	public Anime() {
	}

	public Anime(Autor autor, Clasificacion clasificacion, Genero genero, String nombre) {
		this.autor = autor;
		this.clasificacion = clasificacion;
		this.genero = genero;
		this.nombre = nombre;
	}

	public Anime(Autor autor, Clasificacion clasificacion, Genero genero, String nombre, String sinopsis,
			Integer calificacion, Set<ElencoAnime> elencoAnimes, Set<Capitulo> capitulos) {
		this.autor = autor;
		this.clasificacion = clasificacion;
		this.genero = genero;
		this.nombre = nombre;
		this.sinopsis = sinopsis;
		this.calificacion = calificacion;
		this.elencoAnimes = elencoAnimes;
		this.capitulos = capitulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAnime", unique = true, nullable = false)
	public Integer getIdAnime() {
		return this.idAnime;
	}

	public void setIdAnime(Integer idAnime) {
		this.idAnime = idAnime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAutor", nullable = false)
	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idClasificacion", nullable = false)
	public Clasificacion getClasificacion() {
		return this.clasificacion;
	}

	public void setClasificacion(Clasificacion clasificacion) {
		this.clasificacion = clasificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGenero", nullable = false)
	public Genero getGenero() {
		return this.genero;
	}

	public void setGenero(Genero genero) {
		this.genero = genero;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "sinopsis", length = 60)
	public String getSinopsis() {
		return this.sinopsis;
	}

	public void setSinopsis(String sinopsis) {
		this.sinopsis = sinopsis;
	}

	@Column(name = "calificacion")
	public Integer getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anime")
	public Set<ElencoAnime> getElencoAnimes() {
		return this.elencoAnimes;
	}

	public void setElencoAnimes(Set<ElencoAnime> elencoAnimes) {
		this.elencoAnimes = elencoAnimes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anime")
	public Set<Capitulo> getCapitulos() {
		return this.capitulos;
	}

	public void setCapitulos(Set<Capitulo> capitulos) {
		this.capitulos = capitulos;
	}

}
