package mx.com.quartz.persistence.entities;
// Generated 31/07/2019 10:40:26 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autor generated by hbm2java
 */
@Entity
@Table(name = "Autor", catalog = "garnet")
public class Autor implements java.io.Serializable {

	private Integer idAutor;
	private String nombre;
	private Set<Anime> animes = new HashSet<Anime>(0);

	public Autor() {
	}

	public Autor(String nombre, Set<Anime> animes) {
		this.nombre = nombre;
		this.animes = animes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAutor", unique = true, nullable = false)
	public Integer getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(Integer idAutor) {
		this.idAutor = idAutor;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autor")
	public Set<Anime> getAnimes() {
		return this.animes;
	}

	public void setAnimes(Set<Anime> animes) {
		this.animes = animes;
	}

}
