package mx.com.quartz.persistence.entities;
// Generated 31/07/2019 10:40:26 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clasificacion generated by hbm2java
 */
@Entity
@Table(name = "Clasificacion", catalog = "garnet")
public class Clasificacion implements java.io.Serializable {

	private Integer idClasificacion;
	private String nombre;
	private String descripcion;
	private Set<Anime> animes = new HashSet<Anime>(0);

	public Clasificacion() {
	}

	public Clasificacion(String nombre) {
		this.nombre = nombre;
	}

	public Clasificacion(String nombre, String descripcion, Set<Anime> animes) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.animes = animes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idClasificacion", unique = true, nullable = false)
	public Integer getIdClasificacion() {
		return this.idClasificacion;
	}

	public void setIdClasificacion(Integer idClasificacion) {
		this.idClasificacion = idClasificacion;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 70)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clasificacion")
	public Set<Anime> getAnimes() {
		return this.animes;
	}

	public void setAnimes(Set<Anime> animes) {
		this.animes = animes;
	}

}
