package mx.com.quartz.persistence.entities;
// Generated 31/07/2019 10:40:26 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Elenco generated by hbm2java
 */
@Entity
@Table(name = "Elenco", catalog = "garnet")
public class Elenco implements java.io.Serializable {

	private Integer idElenco;
	private String nombre;
	private Set<ElencoAnime> elencoAnimes = new HashSet<ElencoAnime>(0);

	public Elenco() {
	}

	public Elenco(String nombre) {
		this.nombre = nombre;
	}

	public Elenco(String nombre, Set<ElencoAnime> elencoAnimes) {
		this.nombre = nombre;
		this.elencoAnimes = elencoAnimes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idElenco", unique = true, nullable = false)
	public Integer getIdElenco() {
		return this.idElenco;
	}

	public void setIdElenco(Integer idElenco) {
		this.idElenco = idElenco;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elenco")
	public Set<ElencoAnime> getElencoAnimes() {
		return this.elencoAnimes;
	}

	public void setElencoAnimes(Set<ElencoAnime> elencoAnimes) {
		this.elencoAnimes = elencoAnimes;
	}

}
