package mx.com.quartz.persistence.entities;
// Generated 31/07/2019 10:40:26 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name = "Genero", catalog = "garnet")
public class Genero implements java.io.Serializable {

	private Integer idGenero;
	private String nombre;
	private Set<Anime> animes = new HashSet<Anime>(0);

	public Genero() {
	}

	public Genero(String nombre) {
		this.nombre = nombre;
	}

	public Genero(String nombre, Set<Anime> animes) {
		this.nombre = nombre;
		this.animes = animes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idGenero", unique = true, nullable = false)
	public Integer getIdGenero() {
		return this.idGenero;
	}

	public void setIdGenero(Integer idGenero) {
		this.idGenero = idGenero;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genero")
	public Set<Anime> getAnimes() {
		return this.animes;
	}

	public void setAnimes(Set<Anime> animes) {
		this.animes = animes;
	}

}
